#requires -Version 5.1
$OutputEncoding = [System.Text.Encoding]::UTF8
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

$brain = "C:\Users\Owner\business\brain"
$dispatcher = "$brain\scripts\dispatch.ps1"

# 大井外出ぶん回しwave: 150件・主力5事業×ビジコン×収益×仕様×ブランド
$tasks = @(
    # ===== AIpaX (5社目契約・6/21期限) 20件 =====
    @{ d="marketing"; t="AIpaX 製造業10社 個別メール"; p="# タスク: AIpaX 5社目候補 製造業10社向け個別メール`n[[entities/aipax]] 各社名・規模・接触経路推測・件名+本文400字+CTA・大井1人称・実例「既存4社月20万」" },
    @{ d="marketing"; t="AIpaX 建設業10社 個別メール"; p="# タスク: AIpaX 5社目候補 建設業10社向け個別メール`n[[entities/aipax]] 静岡西部中心・人手不足フック・各社カスタマイズ" },
    @{ d="marketing"; t="AIpaX 介護10社 個別メール"; p="# タスク: AIpaX 介護業界10社向け個別メール`n[[entities/aipax]] シフト管理・離職率フック" },
    @{ d="marketing"; t="AIpaX 物流10社 個別メール"; p="# タスク: AIpaX 物流業界10社向け個別メール`n[[entities/aipax]] 2024年問題後フック" },
    @{ d="marketing"; t="AIpaX 小売チェーン10社 個別メール"; p="# タスク: AIpaX 小売チェーン10社向け個別メール`n[[entities/aipax]] 多店舗管理・店長依存フック" },
    @{ d="newbiz"; t="AIpaX 商談1回目スライド15枚 v2"; p="# タスク: AIpaX 商談1回目スライド15枚 v2`n[[entities/aipax]] 各スライドのコピー+ビジュアル指示+話す内容" },
    @{ d="newbiz"; t="AIpaX 商談2回目デモ動画台本"; p="# タスク: AIpaX 商談2回目用デモ動画台本 5分`n[[entities/aipax]] 保存庫検索→業務AI→社内チャット の流れ" },
    @{ d="newbiz"; t="AIpaX 月次レポート 既存4社カスタム"; p="# タスク: AIpaX 既存4社向け月次レポートテンプレ`n[[entities/aipax]] 業種別 (製造/サービス/医療) 各レポート構成" },
    @{ d="newbiz"; t="AIpaX 既存4社 紹介依頼メール v2"; p="# タスク: AIpaX 既存4社向け 紹介依頼メール v2`n各社業種別カスタマイズ・紹介報酬モデル" },
    @{ d="newbiz"; t="AIpaX 入庫前処理 顧客確認シート"; p="# タスク: AIpaX 顧客確認シート テンプレ`n会社情報20項目・業務フロー10項目・データ可視化希望3項目" },
    @{ d="corp"; t="AIpaX 業務委託契約書 v2"; p="# タスク: AIpaX 業務委託契約書 v2 (5社目用・通常価格)`n初期100-150万・月10-15万・データ保護・解約・反社条項" },
    @{ d="corp"; t="AIpaX ROI試算シート v2"; p="# タスク: AIpaX ROI試算 月50万コンサル vs AIpaX80万比較 v2`n業界別カスタム3版・商談1枚スライド" },
    @{ d="marketing"; t="AIpaX X展開30日戦略"; p="# タスク: AIpaX X 30日展開戦略`n毎日投稿テーマ・時間・大井キャラ反映度" },
    @{ d="marketing"; t="AIpaX LinkedIn営業文5パターン"; p="# タスク: AIpaX LinkedIn 中堅企業向け営業文5パターン`nコネクション依頼+1stメッセージ構成" },
    @{ d="newbiz"; t="AIpaX 5社目クロージング想定問答20問"; p="# タスク: AIpaX 5社目商談 クロージング想定問答20問`n価格・解約・他社比較・社員反発・データ保護・ROI 各300字" },
    @{ d="marketing"; t="AIpaX note記事『AIで月20万削減実例』"; p="# タスク: note記事『AIで月20万削減した中堅企業の話』3000字`n[[entities/aipax]] 既存4社実例・大井1人称・匿名構造" },
    @{ d="research"; t="AIpaX 静岡県内中堅50社プロファイル"; p="# タスク: AIpaX ターゲット 静岡県内中堅50社プロファイル`n業種別・規模・接触経路推測" },
    @{ d="newbiz"; t="AIpaX アップセル提案3パターン v2"; p="# タスク: AIpaX 既存4社 アップセル提案v2`n社内AIチャット・新人教育AI・CS対応AI 各説明" },
    @{ d="marketing"; t="AIpaX 月20万削減事例 構造化"; p="# タスク: AIpaX 月20万削減事例構造化 (匿名)`n4社それぞれの導入前/後・施策・効果数字" },
    @{ d="newbiz"; t="AIpaX 6/21月収100万 残30日緊急シナリオ"; p="# タスク: 月収100万 (6/21期限) 残30日緊急シナリオ`n[[entities/aipax]] [[hot]] 週次目標+施策5本+楽観/標準/悲観" },
    # ===== Testall (β顧客100名) 15件 =====
    @{ d="newbiz"; t="Testall 受験生ペルソナ10パターン詳細"; p="# タスク: Testall 受験生ペルソナ10パターン`n各: 学年・偏差値・志望校・悩み・親関係・継続理由・解約理由" },
    @{ d="newbiz"; t="Testall MVP機能優先順位 9月版"; p="# タスク: Testall MVP機能優先順位 9月リリース版`n5機能の優先順位・各工数・切り捨て基準" },
    @{ d="newbiz"; t="Testall 1日45分プラン自動生成ロジック"; p="# タスク: Testall 1日45分プラン自動生成ロジック`n模試弱点→単元→演習問題→翌日タスク のフロー" },
    @{ d="newbiz"; t="Testall リテンション施策10本"; p="# タスク: Testall 1ヶ月続けるための仕掛け10本`n通知・ご褒美・親共有・ランキング 等" },
    @{ d="marketing"; t="Testall β募集LP 受験生版"; p="# タスク: Testall β募集LP 受験生向け 3500字`nHero/Problem/Solution/Proof/Pricing/CTA" },
    @{ d="marketing"; t="Testall β募集LP 親向け版"; p="# タスク: Testall β募集LP 親向け 2500字`n保護者ペイン3つ→Testall解決3つ→FAQ12問" },
    @{ d="marketing"; t="Testall X投稿『受験あるある』30本"; p="# タスク: Testall X投稿『受験あるある』30本`n大井キャラ・大学受験リアル・Testall自然接続" },
    @{ d="marketing"; t="Testall TikTok台本『塾なし受験』15本"; p="# タスク: Testall TikTok台本『塾なし受験』15本 各60秒`n大井1人称・データ・Testall告知" },
    @{ d="marketing"; t="Testall note記事『塾に行けない受験生』"; p="# タスク: note記事『塾に行けない受験生へ』長編3500字`n[[entities/testall]] 大井原体験・1日45分プラン構造" },
    @{ d="marketing"; t="Testall SEO『塾なし 受験 アプリ』"; p="# タスク: SEO記事『塾なし 受験 アプリ』完全本文 3500字`nKW難易度・上位3社比較・Testall差別化" },
    @{ d="marketing"; t="Testall SEO『模試 弱点 分析 AI』"; p="# タスク: SEO記事『模試 弱点 分析 AI』完全本文 3500字`nKW・競合・Testall機能訴求" },
    @{ d="dev"; t="Testall データモデル v2"; p="# タスク: Testall データモデル仕様 v2`nUser/Score/StudyPlan/Goal/Notification 各テーブル詳細" },
    @{ d="dev"; t="Testall API仕様 v2"; p="# タスク: Testall REST API仕様 v2`n認証・計画生成・進捗・通知の各エンドポイント設計" },
    @{ d="research"; t="Testall vs Studyplus Planning 徹底比較 v2"; p="# タスク: Testall vs Studyplus Planning徹底比較 v2`n[[entities/testall]] 機能/UX/価格/勝ち筋 表" },
    @{ d="research"; t="Testall 受験系インフルエンサー20名リスト"; p="# タスク: Testall 受験系インフルエンサー20名リスト`n登録者10万+・連絡経路・コラボ案" },
    # ===== AIpa Web (モニター3社) 15件 =====
    @{ d="research"; t="AIpa Web 静岡建設業30社具体"; p="# タスク: AIpa Web 静岡県内 建設業30社 具体プロファイル`n[[entities/aipa-web]] 規模・採用課題・接触経路" },
    @{ d="research"; t="AIpa Web 静岡製造業30社具体"; p="# タスク: AIpa Web 静岡県内 製造業30社 具体プロファイル`n[[entities/aipa-web]]" },
    @{ d="research"; t="AIpa Web 静岡サービス業30社具体"; p="# タスク: AIpa Web 静岡県内 サービス業30社 具体プロファイル`n[[entities/aipa-web]]" },
    @{ d="marketing"; t="AIpa Web 接触メール5パターン v2"; p="# タスク: AIpa Web 接触メール5パターン v2`n商工会経由/取引先紹介/コールド/XDM/LinkedIn 各300字" },
    @{ d="marketing"; t="AIpa Web LP 完全版"; p="# タスク: AIpa Web β顧客モニターLP 完全版 4000字`nHero/痛み/解決/16セクション/プラン/事例" },
    @{ d="marketing"; t="AIpa Web 採用業界SEO『中小企業 採用 失敗』"; p="# タスク: SEO記事『中小企業の採用失敗パターン10選』3500字`n[[entities/aipa-web]] CV狙い・モニター15万円自然導線" },
    @{ d="marketing"; t="AIpa Web SEO『中小企業 採用サイト 自社制作』"; p="# タスク: SEO記事『中小企業 採用サイト 自社制作 vs 外注』3500字`n[[entities/aipa-web]]" },
    @{ d="dev"; t="AIpa Web Googleフォーム→DBスキーマ v2"; p="# タスク: AIpa Web 16セクションフォーム→DBスキーマ v2`n各フィールド・型・バリデーション" },
    @{ d="dev"; t="AIpa Web AI応募者対応プロンプト設計"; p="# タスク: AIpa Web 応募者対応AIプロンプト設計`n業界別・面談誘導・断り文 自動化" },
    @{ d="newbiz"; t="AIpa Web モニター15万→月25万移行プラン"; p="# タスク: AIpa Web モニター15万→通常25万移行プラン`n顧客説明書面・タイミング・契約変更フロー" },
    @{ d="newbiz"; t="AIpa Web 月運用『社外Web担当者』業務マニュアル"; p="# タスク: AIpa Web 月運用 業務マニュアル`n社外Web担当者として何やるか 30タスク詳細" },
    @{ d="corp"; t="AIpa Web モニター契約書"; p="# タスク: AIpa Web モニター契約書 (15万円プラン)`n納期・瑕疵・月額移行条件 2500字" },
    @{ d="marketing"; t="AIpa Web 採用テンプレ3種"; p="# タスク: AIpa Web 採用サイトテンプレ3種`n建設/製造/介護 各業界別の構成・コピー" },
    @{ d="research"; t="AIpa Web 競合engage徹底比較"; p="# タスク: AIpa Web vs engage(en-japan) 徹底比較`n[[entities/aipa-web]] 機能/価格/ターゲット/差別化" },
    @{ d="marketing"; t="AIpa Web インスタ広告月3万ターゲティング"; p="# タスク: AIpa Web インスタ広告 月3万円ターゲティング設計`n業界・年齢・地域・キーワード・配信時間" },
    # ===== EEMUS (夢AWARD 6/7) 15件 =====
    @{ d="newbiz"; t="EEMUS 夢AWARD骨子v4 3000字"; p="# タスク: 夢AWARD骨子v4 3000字`n[[entities/eemus]] [[meta/ooi-life-story]] 大井原体験+静岡71%+構造的欠陥+EEMUSの転換" },
    @{ d="newbiz"; t="EEMUS 夢AWARD第1章『私が静岡で見た景色』800字"; p="# タスク: 夢AWARD第1章下書き 800字 1人称`n[[entities/eemus]] 大井原体験・静岡県西部の具体的景色" },
    @{ d="newbiz"; t="EEMUS 夢AWARD第2章『数字が語る構造的欠陥』800字"; p="# タスク: 夢AWARD第2章下書き 800字`n71%/33%/50.8%/79.5%/38.4% 各数字に出典1行" },
    @{ d="newbiz"; t="EEMUS 夢AWARD第3章『既存事業の限界』800字"; p="# タスク: 夢AWARD第3章下書き 800字`nWantedly/マイナビ/地方紙の限界と高校生×中堅企業マッチング市場の空き" },
    @{ d="newbiz"; t="EEMUS 夢AWARD第4章『3つの転換』900字"; p="# タスク: 夢AWARD第4章下書き 900字`n転換1進学一択→選択肢/2企業の採用ミス→入社前/3静岡離れ→地元見える化" },
    @{ d="newbiz"; t="EEMUS 夢AWARD第5章『なぜ私がやるか』800字"; p="# タスク: 夢AWARD第5章下書き 800字`n大井1人称・原体験 + AIpaX実績 + 17歳起業家USP" },
    @{ d="newbiz"; t="EEMUS 夢AWARD第6章『3年後の静岡』700字"; p="# タスク: 夢AWARD第6章下書き 700字`n2029年の絵・連携企業数・参加高校生数・離職率改善" },
    @{ d="marketing"; t="EEMUS 夢AWARD ピッチ60秒台本"; p="# タスク: 夢AWARD 60秒ピッチ動画台本`n[[entities/eemus]] 大井1人称・原体験+数字+涙ポイント+撮影指示" },
    @{ d="marketing"; t="EEMUS 夢AWARD 3分プレゼン台本"; p="# タスク: 夢AWARD 3分プレゼン台本 + 10枚スライド指示" },
    @{ d="marketing"; t="EEMUS β高校5校 営業文"; p="# タスク: EEMUS β高校5校向け 校長/進路指導/PTA各宛 各800字×3" },
    @{ d="newbiz"; t="EEMUS 連携企業20社接触戦略"; p="# タスク: EEMUS 静岡県内連携企業20社 接触戦略`n各社アプローチ順・反応予測・成約率" },
    @{ d="newbiz"; t="EEMUS マッチングロジック仕様"; p="# タスク: EEMUS 高校生×企業マッチングロジック`n属性/興味/距離 ハイブリッド" },
    @{ d="newbiz"; t="EEMUS 高校生インターン体験談3本"; p="# タスク: EEMUS 高校生インターン体験談3本 (構造リアル)`n架空3人・各業界・before/after" },
    @{ d="corp"; t="EEMUS 連携企業契約書"; p="# タスク: EEMUS 連携企業 (高校生インターン) 契約書 2500字`n受入条件・責任分担・保険・解約" },
    @{ d="newbiz"; t="EEMUS 提出書類リスト + テンプレ"; p="# タスク: 夢AWARD 提出書類リスト + 各書類テンプレ`n企画書・収支予算・代表者経歴" },
    # ===== AOF (Agents of Flag) 10件 =====
    @{ d="newbiz"; t="AOF 競技ルール完全版 v2"; p="# タスク: AOF 競技ルール v2 (光線銃+センサー+音+振動+ランク)`n1試合フロー・違反20条・観戦UI・大会形式" },
    @{ d="newbiz"; t="AOF β大会開催プラン (10チーム×4人)"; p="# タスク: AOF β大会 開催プラン詳細`n会場/機材/運営/スポンサー/告知 タイムライン" },
    @{ d="newbiz"; t="AOF ホットスプリングス商談資料 3000字"; p="# タスク: AOF ホットスプリングス面談 提案資料 3000字`n既存機材PoC打診・共同実証スキーム" },
    @{ d="newbiz"; t="AOF スポンサー候補20社リスト"; p="# タスク: AOF スポンサー候補20社リスト`nスポーツ用品・ゲーム・通信・地域企業・各社接触経路" },
    @{ d="newbiz"; t="AOF 静岡PoC会場候補10ヶ所"; p="# タスク: AOF 静岡PoC会場候補10ヶ所`n各: 広さ・賃料・アクセス・条件" },
    @{ d="dev"; t="AOF アプリ仕様 v2"; p="# タスク: AOF アプリ仕様 v2`n戦績・ランク・チーム・予約・観戦・5機能の画面構成" },
    @{ d="newbiz"; t="AOF 機材リスト + 原価試算"; p="# タスク: AOF 機材リスト+原価試算`n光線銃・ベスト・センサー・スクリーン・各単価・10チーム必要量" },
    @{ d="newbiz"; t="AOF 来年Q1着手スケジュール詳細"; p="# タスク: AOF 来年Q1 (2027年1-3月) 着手スケジュール詳細`n月別・タスク・担当・成果物" },
    @{ d="marketing"; t="AOF 投資家向け1分ピッチ動画台本"; p="# タスク: AOF 投資家向け 1分ピッチ動画台本`nリアルFPSスポーツ・市場性・収益・初期投資" },
    @{ d="marketing"; t="AOF note記事『リアルFPS時代の到来』"; p="# タスク: note記事『リアルFPSスポーツの時代』2500字`n[[entities/agents-of-flag]] スポーツビジョン語り" },
    # ===== AIpaX school (第1期5名) 10件 =====
    @{ d="marketing"; t="AIpaX school 体験会2時間プログラム v2"; p="# タスク: AIpaX school 体験会2h プログラム詳細 v2`n中高生5名+親同席・スクリプト・スライド・トリガー" },
    @{ d="marketing"; t="AIpaX school LP USP活用版"; p="# タスク: AIpaX school LP 『17歳現役AI起業家』USP活用 3000字" },
    @{ d="marketing"; t="AIpaX school 中高生TikTok戦略"; p="# タスク: AIpaX school 中高生TikTok戦略`n投稿パターン・コラボ案・10本台本" },
    @{ d="marketing"; t="AIpaX school 親向けFAQ40問"; p="# タスク: AIpaX school 親向けFAQ40問拡張版`n月額・カリキュラム・成果・安全性・解約 各カテゴリ" },
    @{ d="newbiz"; t="AIpaX school 第1期生5名 獲得戦略"; p="# タスク: AIpaX school 第1期生5名 獲得戦略`nXお試し会・親紹介・コンテスト経由 3経路" },
    @{ d="newbiz"; t="AIpaX school カリキュラムv3 12回分"; p="# タスク: AIpaX school カリキュラムv3 12回分詳細`n各回テーマ・ワーク・宿題・親共有" },
    @{ d="newbiz"; t="AIpaX school 卒業後3年ストーリー"; p="# タスク: AIpaX school 卒業生3年後ストーリー (架空3人)`n各人: 入塾前/期間中/卒業後の変化" },
    @{ d="dev"; t="AIpaX school LMS仕様 v1"; p="# タスク: AIpaX school LMS仕様 v1`n生徒管理・カリキュラム・進捗・親レポート" },
    @{ d="corp"; t="AIpaX school 利用規約"; p="# タスク: AIpaX school 利用規約 (月額3万円)`n料金・解約・休塾・親同意・トラブル対応 3000字" },
    @{ d="marketing"; t="AIpaX school note記事『中高生がAI起業家になる』"; p="# タスク: note記事『中高生がAI起業家になる第一歩』3000字" },
    # ===== ビジコン応募準備 15件 =====
    @{ d="newbiz"; t="近畿大START LINE PITCH 応募骨子 6/5締切"; p="# タスク: 近畿大START LINE PITCH 応募骨子`n[[entities/eemus]] AO 1次免除直結・経済学部総合型選抜C" },
    @{ d="newbiz"; t="関西大KUBIC 応募骨子 6月上旬"; p="# タスク: 関西大KUBIC 高校・高専部門 応募骨子`n[[entities/eemus]] 商学部AO直結" },
    @{ d="newbiz"; t="コムロ起業家アワード 応募骨子 6/12"; p="# タスク: コムロ起業家アワード 応募骨子`n[[entities/testall]] 高校生対象・年3回開催" },
    @{ d="newbiz"; t="GTE 応募骨子 6/26"; p="# タスク: GTE 応募骨子`n[[entities/aipax]] 起業体験プログラム" },
    @{ d="newbiz"; t="StartupBase U18 応募骨子 7/1"; p="# タスク: StartupBase U18 応募骨子 [[entities/aipax]]" },
    @{ d="newbiz"; t="KANSAI学生ビジネスアイデア 7/1"; p="# タスク: KANSAI学生ビジネスアイデア 応募骨子 [[entities/aipa-web]]" },
    @{ d="newbiz"; t="TOKYO STARTUP GATEWAY 応募骨子 7/14"; p="# タスク: TOKYO STARTUP GATEWAY 応募骨子`n[[entities/aipax]] 賞金300万・15歳〜OK" },
    @{ d="newbiz"; t="東和薬品 高校生ビジコン 8/19"; p="# タスク: 東和薬品 未来と健康 高校生ビジコン 応募骨子`n[[entities/eemus]] 医療×地域" },
    @{ d="newbiz"; t="成蹊大 高校生ビジコン 9/25"; p="# タスク: 成蹊大学 高校生ビジコン 応募骨子`n最優秀20万・全国高校生2名以上" },
    @{ d="newbiz"; t="日本政策金融公庫 高校生グランプリ 9/24"; p="# タスク: 日本政策金融公庫 高校生グランプリ 応募骨子`n[[entities/aipax]] SFC AO 1次免除直結唯一ルート" },
    @{ d="newbiz"; t="しずおかビジコン 学生部門 10/9"; p="# タスク: しずおかビジコン 学生部門 応募骨子`n[[entities/aipa-web]] 静岡No.1・地元優位" },
    @{ d="newbiz"; t="ビジコン応募テンプレ統一版"; p="# タスク: ビジコン応募 統一テンプレ`n企画書フォーマット・カスタマイズ箇所・所要時間目安" },
    @{ d="newbiz"; t="夢AWARD後の次5ビジコン応募戦略"; p="# タスク: 夢AWARD後 次5ビジコン応募戦略`n7-9月締切ものに集中・各事業優先順位" },
    @{ d="newbiz"; t="ビジコン武勇伝化発信戦略"; p="# タスク: ビジコン武勇伝化発信戦略`n各応募の X/note でのストーリー化" },
    @{ d="newbiz"; t="SFC AO エッセイ骨子v3 30000字構成"; p="# タスク: SFC AO エッセイ骨子v3 30000字構成`n『AIによる思考の外部化と人間の主体性』テーマ・大井実例" },
    # ===== コーディング/仕様 15件 =====
    @{ d="dev"; t="AIpaX 保存庫コア技術仕様 v2"; p="# タスク: AIpaX 会社別AI保存庫 技術仕様 v2`nベクトルDB・RAG・Slack連携・社内Wiki構成" },
    @{ d="dev"; t="AIpaX 業務AIプロンプト設計"; p="# タスク: AIpaX 業務AI プロンプト設計5種`n社内チャット・新人教育・CS対応・電話支援・営業支援" },
    @{ d="dev"; t="Stripe決済 5事業ロードマップ"; p="# タスク: 主力5事業Stripe決済設定ロードマップ`n各: 商品・価格モデル・支払い方法・法的考慮" },
    @{ d="dev"; t="IPAK-darts アプリ仕様 v1"; p="# タスク: IPAK-darts アプリ仕様 v1`n[[entities/ipak-darts]] 入退店QR・予約・課金・会員ランク" },
    @{ d="dev"; t="FishOps Agent システム構成図"; p="# タスク: FishOps Agent システム構成図`n[[entities/ipak-fishing]] 5機能のデータフロー" },
    @{ d="dev"; t="brain dashboard 拡張案 3つ"; p="# タスク: brain dashboard 拡張案`n部署別タスク完了率・Mythos品質トレンド・コスト追跡" },
    @{ d="dev"; t="OpenClaw worker 並列度8基化案"; p="# タスク: OpenClaw worker 並列度4→8基化方法`nGPU共有・メモリ管理・スケジューリング" },
    @{ d="dev"; t="Testall モデルプロンプト設計 v2"; p="# タスク: Testall 学習計画生成プロンプト設計 v2`nLLM活用・エッジケース・フォールバック" },
    @{ d="dev"; t="brain RAG基盤 設計"; p="# タスク: brain RAG基盤 設計`nwiki全文ベクトル化・検索API・Claude統合" },
    @{ d="dev"; t="Recurrent pipeline 改善案"; p="# タスク: Recurrent pipeline 改善案`nDepth別モデル切替・コスト最適化" },
    @{ d="dev"; t="EEMUS マッチングAPI仕様"; p="# タスク: EEMUS マッチングAPI仕様`n属性・興味・距離スコア統合・REST設計" },
    @{ d="dev"; t="AIpaX 月次レポート自動生成"; p="# タスク: AIpaX 月次レポート自動生成 仕様`n顧客別データ集計・Claude要約・PDF化フロー" },
    @{ d="dev"; t="brain Mythos L6 Variants実装案"; p="# タスク: Mythos L6 Variants 実装案`nタスクtier別 (1b/3b/10b相当) dispatch振り分けロジック" },
    @{ d="dev"; t="brain L8 MODA Synthesis 実装案"; p="# タスク: Mythos L8 MODA Synthesis 実装案`nDepth1/2/3 を統合してClaude refineするフロー" },
    @{ d="dev"; t="auto_review 採点モデル精度向上"; p="# タスク: auto_review 採点モデル精度向上`n採点ぶれ・自動キャリブレーション・人間レビュー統合" },
    # ===== 横断/ブランド/CS/紹介 15件 =====
    @{ d="marketing"; t="大井ブランディング戦略v2"; p="# タスク: 大井湧瑛 個人ブランディング戦略v2`n世界のユウエイ物語の章立て・各メディア発信方針・節目10本コンテンツ案" },
    @{ d="marketing"; t="主力5事業 SEO戦略マトリックス"; p="# タスク: 主力5事業 SEO戦略マトリックス`n5事業×競合×KW 30マス・優先記事10本ランキング" },
    @{ d="marketing"; t="SNS全体戦略 事業別役割"; p="# タスク: 主力5事業 SNS全体戦略 事業別役割`nX/note/TikTok/YouTube 各事業マッピング" },
    @{ d="newbiz"; t="メンター・先輩・投資家マッピング v2"; p="# タスク: 大井の人脈マッピング v2`n5層分類・連絡優先順位・直近3ヶ月で連絡すべき5名" },
    @{ d="newbiz"; t="主力5事業 紹介プログラム横断"; p="# タスク: 主力5事業 紹介プログラム横断ルール`n各経路: 報酬率・手続き・顧客側メリット・営業ツール" },
    @{ d="newbiz"; t="解約防止プログラム 横断"; p="# タスク: 解約防止プログラム 主力5事業横断`n解約予兆検知・3ヶ月前/1ヶ月前/1週間前 介入アクション" },
    @{ d="corp"; t="価格戦略 全事業横断 v2"; p="# タスク: 価格戦略 全事業横断 v2`n17事業の現状価格 + 推奨改定・統一感ブランド価格帯" },
    @{ d="corp"; t="主力5事業 月次CF 6月予測"; p="# タスク: 主力5事業 月次キャッシュフロー 2026年6月詳細予測`n各月売上/コスト/純利益/前月比" },
    @{ d="corp"; t="主力5事業 BEP分析"; p="# タスク: 主力5事業 損益分岐点分析`n各事業固定費/変動費/BEP月数" },
    @{ d="corp"; t="副業契約 標準テンプレ3種"; p="# タスク: 副業/業務委託契約 標準テンプレ 3種`nエンジニア/デザイナー/ライター 各2500字" },
    @{ d="corp"; t="主力5事業 補助金活用マップ"; p="# タスク: 主力5事業で使える補助金10件マップ`nIT導入・小規模事業者・事業再構築・各都道府県 各事業の適合度" },
    @{ d="secretary"; t="議事録テンプレ 5パターン v2"; p="# タスク: 議事録テンプレ 5パターン v2`n商談/社内/インタビュー/講義/プロジェクト" },
    @{ d="secretary"; t="日報テンプレ 大井向け1分版 v2"; p="# タスク: 日報テンプレ 大井向け1分版 v2`n進捗/詰まり/明日 3項目 1分で書ける" },
    @{ d="secretary"; t="週次レビューテンプレ 大井向け"; p="# タスク: 週次レビューテンプレ 大井向け`n5事業×3指標 + 来週本命1個 + 棚卸し3項目" },
    @{ d="secretary"; t="email下書きテンプレ 大井キャラ8種"; p="# タスク: メール下書きテンプレ集 大井キャラ反映8種`n初対面/紹介/お断り/感謝/緊急/フォロー/解約/月次報告" },
    # ===== リサーチ (市場/競合/業界) 10件 =====
    @{ d="research"; t="2026年AI市場 国内主要プレイヤー20社"; p="# タスク: 2026年国内AI市場 主要プレイヤー20社`n各社売上・主力サービス・AIpaX競合度" },
    @{ d="research"; t="静岡県 中堅企業100社 デジタル化レポート"; p="# タスク: 静岡県 中堅企業100社 デジタル化レポート`n業種別・規模別・IT投資傾向・採用課題" },
    @{ d="research"; t="HR Tech市場 2026年予測"; p="# タスク: 2026年HR Tech市場 予測`n採用/評価/育成/勤怠 4領域・市場規模・成長率・プレイヤー" },
    @{ d="research"; t="2026年AI規制動向 日本/EU/米国"; p="# タスク: 2026年AI規制動向`n日本AI法案・EU AI Act・米国動向・AIpaX影響" },
    @{ d="research"; t="高校生起業家事例10件 国内"; p="# タスク: 国内高校生起業家10件 (2024-2026)`n各: 名前・学校・事業・規模・メディア露出・大井との比較" },
    @{ d="research"; t="日本ベンチャー投資家トップ20"; p="# タスク: 日本のベンチャー投資家トップ20`nVC/エンジェル・投資領域・直近ディール・大井向きリスト" },
    @{ d="research"; t="EdTech米国Top10 Testall示唆"; p="# タスク: 米国EdTech Top10 2026`nKhan/Duolingo/Coursera 等 + Testall示唆" },
    @{ d="research"; t="日本SaaS課金成功パターン10事例"; p="# タスク: 日本SaaS 課金成功パターン10事例`nfreee/SmartHR/Sansan 等の課金構造・LTV・チャーン率" },
    @{ d="research"; t="2026年中小企業AI業務利用調査"; p="# タスク: 2026年中小企業 生成AI業務利用調査`n業種別・規模別・利用率・主用途・課題" },
    @{ d="research"; t="JR東海エリア中堅企業100社マップ"; p="# タスク: JR東海エリア (静岡/愛知/三重/岐阜) 中堅企業100社マップ`n業種別・AIpaX/AIpa Webスコア" },
    # ===== コンテンツ量産 10件 =====
    @{ d="marketing"; t="X投稿 大井キャラ50本"; p="# タスク: X投稿50本 大井キャラ完全反映`n起業/AI/受験/恋愛/失敗/家族 各テーマ・140字・タグ" },
    @{ d="marketing"; t="TikTok台本 大井17歳起業家ストーリー10本"; p="# タスク: TikTok台本10本『17歳AI起業家』各60秒`n大井実例・AIpaX/AIpaX school自然誘導" },
    @{ d="marketing"; t="YouTube動画台本『17歳AI起業家』10分"; p="# タスク: YouTube動画台本『17歳AI起業家』10分`n大井ストーリー・事業構造・1年後の絵" },
    @{ d="marketing"; t="note記事『AIで月20万削減した中堅企業』2500字"; p="# タスク: note記事 2500字 AIpaX実例" },
    @{ d="marketing"; t="note記事『静岡71%流出』3000字"; p="# タスク: note記事『静岡県外進学71%・Uターン33%の現実』3000字 EEMUSストーリー" },
    @{ d="marketing"; t="LinkedIn投稿20本"; p="# タスク: LinkedIn投稿20本 ビジネスマン向け・大井キャラ・事業話" },
    @{ d="marketing"; t="プレスリリース AIpaX 4社契約済発表"; p="# タスク: プレスリリース AIpaX 4社契約済発表`nメディア向け・PRTimes想定" },
    @{ d="marketing"; t="プレスリリース EEMUS夢AWARD応募"; p="# タスク: プレスリリース EEMUS夢AWARD応募`n静岡ローカルメディア・地域貢献訴求" },
    @{ d="marketing"; t="ピッチ動画台本 大井1分自己紹介"; p="# タスク: ピッチ動画台本 大井1分自己紹介`n17歳・3本柱・実績・志望" },
    @{ d="marketing"; t="ピッチデック 投資家向け10枚"; p="# タスク: 投資家向けピッチデック10枚`n主力3事業・市場・チーム・調達・1分Q&A" }
)

$dispatched = 0
foreach ($t in $tasks) {
    $stamp = (Get-Date).ToString("yyyyMMdd-HHmm")
    $sid = [guid]::NewGuid().ToString().Substring(0,4)
    $slug = ($t.t -replace '[^\w]','-').ToLower()
    if ($slug.Length -gt 40) { $slug = $slug.Substring(0, 40) }
    $outPath = "$brain\wiki\_inbox\$($t.d)\outing-$slug-$stamp-$sid.md"
    & $dispatcher -Department $t.d -Title "[Outing] $($t.t)" -Prompt $t.p -Model "qwen3.6:latest" -OutputPath $outPath -Priority "high" 2>&1 | Out-Null
    $dispatched++
}
Write-Host "Outing wave dispatched: $dispatched tasks"
